apiVersion: ""
generated: "0001-01-01T00:00:00Z"
repositories:
  - caFile: ""
    certFile: ""
    insecure_skip_tls_verify: false
    keyFile: ""
    name: hashicorp
    password: ""
    url: https://helm.releases.hashicorp.com
    username: ""
  - caFile: ""
    certFile: ""
    insecure_skip_tls_verify: false
    keyFile: ""
    name: fluxcd
    password: ""
    url: https://fluxcd.github.io/flux
    username: ""

